### ISSUE TITLE
Improve the validation of manifest.json (e.g. with a JSON Schema)

### ISSUE THREAD

**Issue by sxren** [openc/turbot-client#17]
Error:       undefined method `include?' for nil:NilClass (NoMethodError)
    Backtrace:   /Users/user/.gem/ruby/1.9.3/gems/turbot-runner-0.1.14/lib/turbot_runner/processor.rb:56:in `block in validate'
                 /Users/user/.gem/ruby/1.9.3/gems/turbot-runner-0.1.14/lib/turbot_runner/processor.rb:55:in `reject'
                 /Users/user/.gem/ruby/1.9.3/gems/turbot-runner-0.1.14/lib/turbot_runner/processor.rb:55:in `validate'
                 /Users/user/.gem/ruby/1.9.3/gems/turbot-runner-0.1.14/lib/turbot_runner/processor.rb:20:in `process'
                 /Users/user/.gem/ruby/1.9.3/gems/turbot-runner-0.1.14/lib/turbot_runner/script_runner.rb:55:in `run'
                 /Users/user/.gem/ruby/1.9.3/gems/turbot-runner-0.1.14/lib/turbot_runner/runner.rb:72:in `run_script'
                 /Users/user/.gem/ruby/1.9.3/gems/turbot-runner-0.1.14/lib/turbot_runner/runner.rb:23:in `block in run'
                 /Users/user/.gem/ruby/1.9.3/gems/turbot-runner-0.1.14/lib/turbot_runner/runner.rb:22:in `each'
                 /Users/user/.gem/ruby/1.9.3/gems/turbot-runner-0.1.14/lib/turbot_runner/runner.rb:22:in `run'
                 /Users/user/.gem/ruby/1.9.3/gems/turbot-0.1.9/lib/turbot/command/bots.rb:216:in `validate'
                 /Users/user/.gem/ruby/1.9.3/gems/turbot-0.1.9/lib/turbot/command.rb:219:in `run'
                 /Users/user/.gem/ruby/1.9.3/gems/turbot-0.1.9/lib/turbot/cli.rb:28:in `start'
                 /Users/user/.gem/ruby/1.9.3/gems/turbot-0.1.9/bin/turbot:17:in `<top (required)>'
                 /Users/user/.gem/ruby/1.9.3/bin/turbot:23:in `load'
                 /Users/user/.gem/ruby/1.9.3/bin/turbot:23:in `<main>'

    Command:     turbot bots:validate
    Version:     turbot-gem/0.1.9 (x86_64-darwin14.0.0) ruby/1.9.3

**Comment by inglesp** [comment]
Hi @sxren, thanks for reporting this.  I think this might be a bad (terrible!) error message caused by the `identifying_fields` parameter in your manifest being missing.  Can you confirm this is the case?

**Comment by inglesp** [comment]
I've just found your bot's code on the server, and the problem's caused by your `manifest.json` not specifying the `identifying_fields` for your transformer.

Could you fix up your manifest and then push again?  I'll make sure that we give better error messages from the client.

**Comment by sxren** [comment]
Hi, Peter,

There is no guaranteed unique field. Is it OK to use name?

Thanks,
Søren

**Comment by jpmckinney** [comment]
Although Turbot [checks for the presence of `identifying_fields`](https://github.com/openc/turbot-client/blob/e629de1fb17ba05eca932c89f5e609c9c0c46c3b/lib/turbot/command/bots.rb#L204), it should also check that it is an Array.

**Comment by jpmckinney** [comment]
Noting that I had a typo `data-type` under `transformers` which wasn't noticed, but which a JSON Schema would pick up easily.
