### ISSUE TITLE
Generating or registering a bot with a dot in its name prints a confusing error message.

### ISSUE THREAD

**Issue by saljam** [openc/turbot-client#18]
Removing the dots makes it work again. A nicer error message would be nice. :)

    $ turbot bots:generate --bot cma.org.sa
     !    Turbot client internal error.
     !    Report a bug at: https://github.com/openc/turbot-client/issues/new
    
        Error:       757: unexpected token at '<?xml version="1.0" encoding="UTF-8"?>
    <hash>
      <status>404</status>
      <error>Not Found</error>
    </hash>
    ' (JSON::ParserError)
        Backtrace:   /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/json/common.rb:155:in `parse'
                 /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/json/common.rb:155:in `parse'
                 /usr/local/lib/ruby/gems/2.1.0/gems/turbot-api-0.0.14/lib/turbot_api/api.rb:142:in `initialize'
                 /usr/local/lib/ruby/gems/2.1.0/gems/turbot-api-0.0.14/lib/turbot_api/api.rb:114:in `new'
                 /usr/local/lib/ruby/gems/2.1.0/gems/turbot-api-0.0.14/lib/turbot_api/api.rb:114:in `rescue in request'
                 /usr/local/lib/ruby/gems/2.1.0/gems/turbot-api-0.0.14/lib/turbot_api/api.rb:106:in `request'
                 /usr/local/lib/ruby/gems/2.1.0/gems/turbot-api-0.0.14/lib/turbot_api/api.rb:42:in `show_bot'
                 /usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/turbot-0.1.7/lib/turbot/command/bots.rb:97:in `generate'
                 /usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/turbot-0.1.7/lib/turbot/command.rb:219:in `run'
                 /usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/turbot-0.1.7/lib/turbot/cli.rb:28:in `start'
                 /usr/local/lib/ruby/gems/2.1.0/gems/turbot-0.1.7/bin/turbot:17:in `<top (required)>'
                 /usr/local/bin/turbot:23:in `load'
                 /usr/local/bin/turbot:23:in `<main>'

    Command:     turbot bots:generate --bot cma.org.sa
    Version:     turbot-gem/0.1.7 (x86_64-darwin14.0) ruby/2.1.5

**Comment by inglesp** [comment]
You're certainly right about the error message!  At the least, we should fix that, but I don't see any reason why we shouldn't also allow dots in a bot's name.  Will investigate.  Thanks for the report!

**Comment by jpmckinney** [comment]
Noting that a small number of existing bots contain periods.
