### ISSUE TITLE
Delete a "in_development" turbot

### ISSUE THREAD

**Issue by bertocq** [openc/turbot-client#19]
I can't see a command or web option to delete a turbot, even if it is "in_development". 

I made a test locally but never submitted it because as a group we made a second bot for the mission.

PD: Turbot name is "turbotron" ;)

**Comment by sebbacon** [comment]
You're right, there isn't an option for this - and there should be!

In the interim, we have deleted this for you. Thanks!

**Comment by jpmckinney** [comment]
I made it so that `bots:generate` doesn't immediately register the bot (which wasn't documented behavior), so when testing/developing a bot, it's possible to abandon the work without cluttering Turbot.

**Comment by shyamperi** [comment]
:+1:
