### ISSUE TITLE
Why use specific versions of turbot-runner instead of ~>?

### ISSUE THREAD

**Issue by jpmckinney** [openc/turbot-client#40]
If we use e.g. `~> 0.2.7` instead of `0.2.7` then we won't have to update turbot-client everything we make a minor change to turbot-runner (like, for instance, updating some schema).

**Comment by sebbacon** [comment]
Yep. No reason, just people getting  used to waving a dead chicken without thinking about it. Thanks for the fresh eyes :)

**Comment by jpmckinney** [comment]
#41 contains fix.
