### ISSUE TITLE
turbot bots:preview crashes

### ISSUE THREAD

**Issue by k-nut** [openc/turbot-client#5]
Running `turbot bots:preview` results in:
```
Sending to turbot... 
Starting scrape...
..
Sent 30 records.
 !    Turbot client internal error.
 !    Report a bug at: https://github.com/openc/turbot-client/issues/new

    Error:       undefined method `[]' for nil:NilClass (NoMethodError)
    Backtrace:   /var/lib/gems/1.9.1/gems/turbot-0.0.42/lib/turbot/command/bots.rb:357:in `handle_successful_run'
                 /var/lib/gems/1.9.1/gems/turbot-runner-0.0.8/lib/turbot_runner.rb:79:in `run'
                 /var/lib/gems/1.9.1/gems/turbot-0.0.42/lib/turbot/command/bots.rb:280:in `preview'
                 /var/lib/gems/1.9.1/gems/turbot-0.0.42/lib/turbot/command.rb:219:in `run'
                 /var/lib/gems/1.9.1/gems/turbot-0.0.42/lib/turbot/cli.rb:28:in `start'
                 /var/lib/gems/1.9.1/gems/turbot-0.0.42/bin/turbot:17:in `<top (required)>'
                 /usr/local/bin/turbot:23:in `load'
                 /usr/local/bin/turbot:23:in `<main>'

    Command:     turbot bots:preview
    Version:     turbot-gem/0.0.42 (x86_64-linux) ruby/1.9.3
```
Running ```turbot bots:validate``` runs without errors.
My bot is the following: https://gist.github.com/k-nut/19104da704abf7c3f330
And the manifest.json is: https://gist.github.com/k-nut/df5a51f473074b3b2f55

**Comment by morenoh149** [comment]
should be reopened if someone expresses interest in a close issue no?

**Comment by sebbacon** [comment]
Thanks for the reminder @morenoh149

**Comment by inglesp** [comment]
I've had another look at this, and with the same version of turbot as @morenoh149, I get a sensible error message:

    12:37:01 ~/work/openc/bots $ turbot --version
    turbot-gem/0.1.6 (x86_64-darwin10.8.0) ruby/1.9.3
    12:37:07 ~/work/openc/bots $ turbot bots:generate --bot example_1 --language=ruby
     !    There's already a bot called example_1 registered with Turbot. Bot names must be unique.

The code on the server for dealing with this hasn't changed for months, so the problem must be something else.  Unfortunately, we've lost the logs from when @morenoh149 originally saw this.

@morenoh149: are you able to reproduce?

Many thanks!

**Comment by morenoh149** [comment]
I'll need some time. I've also got a feeling you guys fixed this after I experienced it.

**Comment by morenoh149** [comment]
you should close this. I don't have the bandwidth to test this now. Apologies.

**Comment by inglesp** [comment]
Ok, thanks.
